include: package:lint/strict.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/lib_extism.dart"
    - "**/manifest.dart"
